# Generated by Django 3.2.14 on 2022-07-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alltodos_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alltodos',
            name='author',
        ),
        migrations.AddField(
            model_name='alltodos',
            name='tag',
            field=models.CharField(default='General', max_length=15),
        ),
    ]
