# Generated by Django 3.2.14 on 2022-07-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20220719_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltodos',
            name='Status',
            field=models.CharField(choices=[('Completed', 'C'), ('Pending', 'P')], default='Pending', max_length=10),
        ),
    ]
