# Generated by Django 3.2.14 on 2022-07-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alltodos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltodos',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
